language: python
python:
  - "2.6"

sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- pdflatex -interaction=nonstopmode -halt-on-error test.tex && bibtex test.aux && pdflatex -interaction=nonstopmode -halt-on-error test.tex
- ./validate.py
