import bibtexparser
import json

from collections import OrderedDict


papers = dict()

mavlabpapers = {}


parser = bibtexparser.bparser.BibTexParser(common_strings=True)
with open('./website/all.bib', encoding="utf8") as bibtex_file:
    bibtex_str = bibtex_file.read()

bib_database = bibtexparser.loads(bibtex_str, parser=parser)

delfly_database = bibtexparser.bibdatabase.BibDatabase()
rest = bibtexparser.bibdatabase.BibDatabase()

print('================================================================')

for b in bib_database.entries:
    #print(b)
    if  not ('author' in b) or not ('title' in b):
        print('ERROR!', b)
        print('------------------------------------------------------------------------')
        continue


    # Paper
    title = b['title']
    authors = b['author']
    delflypaper = False

    if 'delfly' in title.lower():
        delflypaper = True
    
    if 'flapping' in title.lower():
        delflypaper = True

    if 'fling' in title.lower():
        delflypaper = True

    if 'karasek' in authors.lower():
        delflypaper = True

    if delflypaper:
        delfly_database.entries.append(b)
    else:
        rest.entries.append(b)

print(mavlabpapers)
    

# dump back
writer = bibtexparser.bwriter.BibTexWriter()
writer.indent = '\t'     # indent entries with 4 spaces instead of one
writer.order_entries_by = 'year'
writer.align_values = True
with open('website/delfly.bib', 'w', encoding='utf8') as bibfile:
    bibfile.write('# AUTOGENERATED\n# \n\n')
    bibfile.write(writer.write(delfly_database).replace('&','\&'))


writer = bibtexparser.bwriter.BibTexWriter()
writer.indent = '\t'     # indent entries with 4 spaces instead of one
writer.order_entries_by = 'year'
writer.align_values = True
with open('website/not_delfly.bib', 'w', encoding='utf8') as bibfile:
    bibfile.write('# AUTOGENERATED\n# \n\n')
    bibfile.write(writer.write(rest).replace('&','\&'))
    
print('Done')
