import csv
import requests
# Store FILE
import codecs
from unidecode import unidecode


#############################################################
# V1
# For all pages
# Collect all  'href="/record/uuid:'
# The line below is the Title

MAVLAB = ['wagter' , 'croon', 'remes',
            'karasek', 'smeur',  'dupeyroux',
            'hamaza', '"Scheper, K.Y.W."', '"popovic, marija"']

search = '%20OR%20'.join(MAVLAB)
url = 'https://repository.tudelft.nl/islandora/search/' + search + '?collection=education&display=tud_csv'

print(' - V1:', url)

#############################################################
# V2

MAVLAB = ['wagter' , 'croon', 'remes',
            'karasek', 'smeur',  'dupeyroux',
            'hamaza', '"Scheper, K.Y.W."', 'popovic']


url2 = "https://repository.tudelft.nl/search?search_term=wagter+OR+croon+OR+smeur+OR+remes+OR+popovic&page=1&sort=relevance&record_type=master_thesis"

search = "+OR+".join(MAVLAB)
url2 = "https://repository.tudelft.nl/search?search_term=" + search + "&page=1&sort=relevance&record_type=master_thesis"

print(' - V2:', url2)

#############################################################
# V3

Authors = {
    'croon': 'https://repository.tudelft.nl/person/supervised/Person_c7471550-0ab7-415d-b600-6aab41b170ce', # ?page=1
    'wagter': 'https://repository.tudelft.nl/person/supervised/Person_283a4bdd-9d21-4e56-9f7c-d83c582f6032',
    'smeur': 'https://repository.tudelft.nl/person/supervised/Person_5b52f579-173a-4ba6-9692-5a13e80e29db',
    'remes': 'https://repository.tudelft.nl/person/supervised/Person_82e35d90-9b89-4e86-8a61-74f4fdd86b64',
    'karasek': 'https://repository.tudelft.nl/person/supervised/Person_2f0b1c3d-4a5e-4f6b-8d7c-9e0a1f3c5b2b',
    'hamaza': 'https://repository.tudelft.nl/person/supervised/Person_c2be371b-2204-410d-8d16-af98b68972ff',
    'popovic': 'https://repository.tudelft.nl/person/supervised/Person_8588464f-4d22-4ba2-a530-50d9a50b2554'
}

msc_thesis = "?object_type=master_thesis"

for author in Authors:
    url = Authors[author] + msc_thesis
    print(' -', author, url)

###


def msc_download_to_csv():

    p=0
    p = requests.get(url) # + '&page=%d' % pageno)

    with open('msc.csv', 'wb') as f:
        f.write(p.text.encode())
    txt = p.text

    print('Downloaded...\n')
    #print(txt.encode('UTF-8'))



# msc_download_to_csv()

with open('msc.csv', 'rb') as f:
    txt = f.read().decode('utf-8')


# Create bib
bibf = codecs.open('msc.bib','w', 'utf-8')
bibf.write(u'\ufeff')
bibf.write('# AUTOGENERATED\n# Import from: '+url+'\n\n\n')

reader = csv.reader(txt.split('\n'), delimiter=',')

# Parse the header: store the column names and their index
header = next(reader)
header_indices = {name: idx for idx, name in enumerate(header)}
print(header_indices)


for row in reader:
    if len(row) > 0:
        s = 1

#         if '(' in row[3]:
#             s = row[3].split('(')
#             name = s[0]
#             school = s[1]
#         else:
#             name = row[3]
#             school = 'Delft University of Technology'

#         # Extra checks: names should not be in the abstract but only in supervision
#         good = False
#         for M in MAVLAB:
#             MM = M.lower().replace('"','')
#             if MM in unidecode(row[4].lower()):
#                 good = True
#                 break

#         if good:

#             bibf.write('@mastersthesis{'+row[0]+',\n')
#             bibf.write('\tabstract  = {'+row[6]+'},\n')
#             bibf.write('\tauthor    = {'+name+'},\n')
#             bibf.write('\tkeywords  = {'+row[7]+'},\n')
#             bibf.write('\tnote      = {'+row[4]+'},\n')
#             bibf.write('\tschool    = {'+school.replace(')','')+'},\n')
#             bibf.write('\ttitle     = {'+row[2]+'},\n')
#             bibf.write('\ttype      = {mathesis},\n')
#             bibf.write('\turl       = {'+row[1]+'},\n')
#             bibf.write('\tyear      = {'+row[5]+'}\n')
#             bibf.write('}\n\n')

#         #print(row[2])


bibf.close()
