import csv
import codecs

from import_repository import url2_msc, url2_phd


def csv2bib(csv_file , bib_file):

    with open(csv_file, 'rb') as f:
        txt = f.read().decode('utf-8')


    # Create bib
    bibf = codecs.open(bib_file,'w', 'utf-8')
    bibf.write(u'\ufeff')
    bibf.write('# AUTOGENERATED\n# Import from: '+url2_msc+'\n\n\n')

    reader = csv.reader(txt.split('\n'), delimiter=';')

    # Parse the header: store the column names and their index
    header = next(reader)
    # print('Header:', header)
    header_indices = {name: idx for idx, name in enumerate(header)}
    print(header_indices)

    # Sort the rows by publication date (newest first)
    rows = sorted(reader, key=lambda r: r[header_indices['publication_date']], reverse=True)


    print("title", header_indices['title'])
    count = 0
    for row in rows:
        if len(row) > 0:
            count += 1
            
            d = row[header_indices['publication_date']]
            year = d.split('-')[0] if '-' in d else d
            name = row[header_indices['contributor_names']]
            role = row[header_indices['contributor_roles']]
            notes = d + ": " + name + " -> " + role + " -> " + row[header_indices['contributor_affiliations']]
            if ";" in name:
                name = name.split(';')[0]
            school = "Delft University of Technology"
            title = row[header_indices['title']]
            keywords = row[header_indices['filtered_keywords']]
            abstract = row[header_indices['description']]
            url = row[header_indices['repository_link']]
            #Bugfix
            url =url.replace('uuid:uuid:', 'uuid:')

            pub_type = row[header_indices['publication_type']]
            isMsc = pub_type == 'master thesis'


            if isMsc:
                bibf.write('@mastersthesis{'+row[header_indices['uuid']] + ',\n')
            else:
                bibf.write('@phdthesis{'+row[header_indices['uuid']] + ',\n')
            bibf.write('\tabstract  = {'+abstract+'},\n')
            bibf.write('\tauthor    = {'+name+'},\n')
            # bibf.write('\trole       = {'+role+'},\n')
            bibf.write('\tkeywords  = {'+keywords+'},\n')
            bibf.write('\tnote      = {'+notes+'},\n')
            bibf.write('\tschool    = {'+school+'},\n')
            bibf.write('\ttitle     = {'+title+'},\n')
            if isMsc:
                bibf.write('\ttype      = {mathesis},\n')
            bibf.write('\turl       = {'+url+'},\n')
            bibf.write('\tyear      = {'+year+'}\n')
            bibf.write('}\n\n')


    bibf.close()

    print('Done. Total records:', count)


if __name__ == '__main__':

    csv2bib('./pure/msc.csv', 'msc_new.bib')
    csv2bib('./pure/phd.csv', 'phd.bib')